//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp14
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int report_id { get; set; }
        public Nullable<int> total_requests { get; set; }
        public Nullable<int> avg_resolution_time { get; set; }
    }
}
